// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuhB5-_SId6mabINXdpenGn_1pK9o4z7s',
    appId: '1:316987157191:web:3d1ac840b2f2f97d0bace2',
    messagingSenderId: '316987157191',
    projectId: 'flashchat-5e6f7',
    authDomain: 'flashchat-5e6f7.firebaseapp.com',
    storageBucket: 'flashchat-5e6f7.appspot.com',
    measurementId: 'G-WR4BG4TGKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_YlKedw-pwBeYRs5RnPWSCPH8kxD-c0',
    appId: '1:316987157191:android:440a619a03dee29a0bace2',
    messagingSenderId: '316987157191',
    projectId: 'flashchat-5e6f7',
    storageBucket: 'flashchat-5e6f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJVio_G6ggcNgFYtkacbeC0yW66_DfVY8',
    appId: '1:316987157191:ios:331d642106c53d5b0bace2',
    messagingSenderId: '316987157191',
    projectId: 'flashchat-5e6f7',
    storageBucket: 'flashchat-5e6f7.appspot.com',
    iosClientId: '316987157191-q4nkh5lkph3ukv74scgg95co5rpcr9at.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJVio_G6ggcNgFYtkacbeC0yW66_DfVY8',
    appId: '1:316987157191:ios:331d642106c53d5b0bace2',
    messagingSenderId: '316987157191',
    projectId: 'flashchat-5e6f7',
    storageBucket: 'flashchat-5e6f7.appspot.com',
    iosClientId: '316987157191-q4nkh5lkph3ukv74scgg95co5rpcr9at.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchat',
  );
}
